# Generated by Django 3.2.23 on 2024-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvtushu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
