# Generated by Django 5.1.6 on 2025-03-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinfo",
            name="addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.address",
                verbose_name="地址",
            ),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="ordergoods",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orderinfo",
                verbose_name="订单",
            ),
        ),
    ]
