# Generated by Django 5.1.6 on 2025-02-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Custom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phonenumber", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
