# Generated by Django 5.1.6 on 2025-02-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Custom",
            new_name="Customer",
        ),
    ]
